package ru.tech.prokitchen.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00658a)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFc2e8ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001e2c)
val md_theme_light_secondary = Color(0xFF00687a)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFa6eeff)
val md_theme_light_onSecondaryContainer = Color(0xFF001f26)
val md_theme_light_tertiary = Color(0xFF6750a4)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFeaddff)
val md_theme_light_onTertiaryContainer = Color(0xFF22005d)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFF78d1ff)

val md_theme_dark_primary = Color(0xFF78d1ff)
val md_theme_dark_onPrimary = Color(0xFF003549)
val md_theme_dark_primaryContainer = Color(0xFF004c69)
val md_theme_dark_onPrimaryContainer = Color(0xFFc2e8ff)
val md_theme_dark_secondary = Color(0xFF54d7f3)
val md_theme_dark_onSecondary = Color(0xFF003640)
val md_theme_dark_secondaryContainer = Color(0xFF004e5c)
val md_theme_dark_onSecondaryContainer = Color(0xFFa6eeff)
val md_theme_dark_tertiary = Color(0xFFd0bcff)
val md_theme_dark_onTertiary = Color(0xFF381e73)
val md_theme_dark_tertiaryContainer = Color(0xFF4f378b)
val md_theme_dark_onTertiaryContainer = Color(0xFFeaddff)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inversePrimary = Color(0xFF00658a)